sudo: false
language: python
env: RUNNER=travis
addons:
  firefox: "31.0"
python:
  - "2.7"
install: pip install -r requirements/testing.txt --download-cache $HOME/.pip-cache
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -c "create extension postgis"
script: coverage run  manage.py test
after_success:
  - coveralls
cache:
  directories:
    - /home/travis/virtualenv
    - $HOME/.pip-cache/
addons:
  postgresql: "9.3"